aadams1605/Travel_Tribe

app/models/event.rb, db/migrate/20230828145130_add_user_reference_to_notifications.rb, db/schema.rb
Added user_id reference to notifications table
=> Generate models

app/controllers/chatrooms_controller.rb, app/controllers/events_controller.rb, app/controllers/messages_controller.rb, app/controllers/notifications_controller.rb, app/controllers/requests_controller.rb, app/controllers/users_controller.rb, app/models/event.rb, app/models/message.rb, app/models/user.rb, test/controllers/chatrooms_controller_test.rb, test/controllers/events_controller_test.rb, test/controllers/messages_controller_test.rb, test/controllers/notifications_controller_test.rb, test/controllers/requests_controller_test.rb, test/controllers/users_controller_test.rb
added validations to the model
=> Validations

app/controllers/events_controller.rb, app/views/events/_form.html.erb, app/views/events/new.html.erb
filled in event controller and view files for new and create
=> filled in event controller and view files for new and create

app/controllers/events_controller.rb, app/views/devise/registrations/new.html.erb, app/views/events/index.html.erb
added fields in form
removed = in index view of events
changed index Event.all
=> updated form fields

app/controllers/events_controller.rb
adding a couple other columns to the create method (title and capacity)
=> adding a couple other columns to the create method

app/controllers/accounts_controller.rb, app/controllers/requests_controller.rb, app/views/accounts/show.html.erb, app/views/events/index.html.erb, app/views/events/show.html.erb, config/routes.rb
I have added functionality of:
1) Join event to event page
2)Accept and reject requests in the dashboard/account page.
=> Addingrequests

app/models/chat_participant.rb, app/models/chatroom.rb, app/models/event.rb, app/models/user.rb, db/seeds.rb
changed association in the models to be able to destroy dependencies.
=> updated dependent destroy

app/assets/stylesheets/components/_map.scss, app/controllers/events_controller.rb, app/javascript/controllers/events_map_controller.js, app/views/events/_events_map.html.erb, app/views/events/_info_window.html.erb, app/views/events/index.html.erb, app/views/layouts/application.html.erb, db/schema.rb
add the map  in the index with markers (events) and pop ups
=> map displaying in index page plus popop up

app/models/event.rb, app/views/events/index.html.erb
uncomment some code that need to be present, deleted render search partial, add if statement to cl_image_tag cause our seeds dont have images
=> fix some issues that were breaking the code

app/assets/stylesheets/components/_navbar.scss, app/controllers/notifications_controller.rb, app/controllers/requests_controller.rb, app/models/notification.rb, app/views/notifications/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Created notifications : 
1)when user asks to join an event, event owner receives notification to approve
2)when request gets approved , request owner receives notification if approved or rejected
Styling of Nav bar, to show nicely in mobile version
=> working notifications

app/assets/stylesheets/components/_map.scss, app/controllers/events_controller.rb, app/javascript/controllers/toggle_controller.js, app/views/events/index.html.erb
add a toggle "button" to show the map in the index page
=> toggle button for map in index page

app/models/user.rb, app/views/devise/registrations/new.html.erb
=> Add cloudinary new file

app/views/events/show.html.erb
event page is now showing if we have no images
=> event page is now working when theres no image

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
created footer
white letters
sticky
=> footer ready

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/views/events/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
navbar style, add logo name, re size navbar, add cloudinary avatar,  sign up- sign in
=> navbar style and cloudinary

app/controllers/users_controller.rb, app/views/users/show.html.erb
Created initial user show page
=> Created initial user show page

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/accounts/_show.scss, app/models/chatroom.rb, app/views/accounts/show.html.erb
styled the dashboard view page
=> styled dashboard

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/javascript/controllers/events_map_controller.js, app/javascript/controllers/toggle_controller.js, app/views/events/_events_map.html.erb, app/views/events/_info_window.html.erb, app/views/events/index.html.erb, app/views/shared/_navbar.html.erb
navbar is fixed on the top of the page, index page style
=> index page style, navbar fixed on top

app/views/users/show.html.erb
Created some initial user styling on the show page
=> Created some initial user styling on the show page

app/views/shared/_navbar.html.erb
add a default picture for the avatar when the user dont upload a photo
=> added a default photo for the avatar

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/events/_show.scss, app/views/events/index.html.erb, app/views/events/show.html.erb
I added some styling to the chatroom on each event page.
=> Added styling to chatroom for each event

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/accounts/_show.scss, app/controllers/accounts_controller.rb, app/javascript/controllers/toggle_controller.js, app/views/accounts/show.html.erb
created toggle functionality for dashboard of user
=> Morestylingdashboard

app/assets/stylesheets/components/_card.scss, app/views/users/index.html.erb
Created some styling for the user index.
=> Created some styling for the user index

app/views/accounts/show.html.erb, app/views/shared/_navbar.html.erb
added dropdown link to profile
updated welcome text
=> Addprofiledrop

app/views/users/index.html.erb
consistent style index page and search bar
=> users index style and search bar fixed

app/controllers/events_controller.rb, config/environments/production.rb
Updating to reflect changes made via Heroku.
=> Ben heroku changes

config/locales/devise.en.yml
Deleted log-in/out alerts as unnecessary given the avatar photo.
=> deleted log-in/out alerts as unnecessary given the avatar photo

app/assets/stylesheets/components/_card.scss, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/events/_info_window.html.erb, app/views/events/index.html.erb, app/views/events/show.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, db/seeds.rb
add method capitalize to save usernames with capital letters. Also save seeds with capital letters
=> Seed capitalize

app/javascript/controllers/datepicker_controller.js, app/views/events/_form.html.erb, app/views/events/new.html.erb, app/views/layouts/application.html.erb, config/importmap.rb
add calendar to event form - create event
=> add calendat to event form

app/controllers/chatrooms_controller.rb, app/controllers/events_controller.rb, app/controllers/messages_controller.rb, app/javascript/controllers/chatroom_subscription_controller.js, app/views/chatrooms/show.html.erb, app/views/events/show.html.erb, app/views/messages/_new.html.erb
MIved the chatroom to it´s own dedicated show page and a link to it on the events show. Also added an event listener to recognise "Enter" to submit a new message on the chatroom
=> Moved chatroom to dedicated show page and added event listener 

app/controllers/events_controller.rb, app/views/events/show.html.erb
Added a link to events show to each events chatroom, that only appears if the user is an attendee of the event
=> Added conditional link to chatroom to events

app/views/messages/_messages.html.erb
Added a user avatar to chat messages
=> added user avatar to chat messages

Gemfile, Gemfile.lock, app/controllers/chatrooms_controller.rb, app/controllers/messages_controller.rb, app/controllers/users_controller.rb, app/models/chatroom.rb, app/views/chatrooms/show.html.erb, app/views/events/show.html.erb, app/views/messages/_new.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20230904140306_remove_null_fulse_from_foreign_key.rb, db/schema.rb
Users can now chat privately in a one to one chat
=> Implemented user to user chat functionality

app/controllers/events_controller.rb, app/models/event.rb, app/views/accounts/show.html.erb, app/views/events/show.html.erb
Updated to reflect when the capacity is full, to reject further requests.
=> Updated to reflect when the capacity is full, to reject further requests

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/events/_show.scss, app/views/events/_events_map.html.erb, app/views/events/index.html.erb, app/views/events/show.html.erb
index and show events page styling. Add participants and who post event, they link to profile.
=> events show and index style

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/views/users/index.html.erb, app/views/users/show.html.erb
frontend user show and index page
=> user index and show page style

app/assets/stylesheets/components/_form_legend_clear.scss, app/views/devise/sessions/new.html.erb
added styling to the singin form as we have on signup page.
=> Stylesigninform

app/assets/stylesheets/components/_link.scss, app/assets/stylesheets/pages/accounts/_show.scss, app/controllers/accounts_controller.rb, app/views/accounts/show.html.erb
Pushed initial CSS changes to show page.
=> Pushing initial CSS changes to show page

app/assets/stylesheets/components/_form_legend_clear.scss
Added margin to the forms.
Chnaged color to white in texts so it is more readable.
=> added margins bottom right left and changed color

app/views/events/show.html.erb
Fixed the event chat button to also show to the creator of the event, and removed a duplicate button
=> Fixed button to show event chat to creator

app/views/events/show.html.erb
Updated the text to change from "other attendants" to "attendees".
=> Updated the text to change from other attendants to attendees

app/controllers/notifications_controller.rb, app/views/notifications/index.html.erb
Each notification now has a link that will take you to an event if it is an event notification, or the chatroom if it is a message notification
=> added links to notifications to take you to appropriate page

app/assets/stylesheets/components/_map.scss
aligned map in the homepage for events search.
=> aligned map and text in homepage

app/assets/stylesheets/components/_chatroom.scss, app/controllers/chatrooms_controller.rb, app/views/chatrooms/show.html.erb
Improved appearance of chatroom and changed title to either be the name of the event or of the user if direct chat
=> Improved chatroom styling

app/assets/stylesheets/pages/accounts/_show.scss, app/views/accounts/show.html.erb
Added some styling to the user account page.
=> Added some styling to the user account page

app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/controllers/notifications_controller.rb, app/views/notifications/index.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20230905104252_add_read_to_notifications.rb, db/schema.rb
add new notification icon when user receive new notification. To navbar and notifications index
=> add new notification icon

app/views/events/show.html.erb
=> styling event chat button

app/assets/stylesheets/components/_link.scss, app/views/notifications/index.html.erb
Fixed errors on notifications index
=> Fixed error on notifications index

app/assets/stylesheets/components/_form_legend_clear.scss
Added margin in the buttons of the log in page
=> added margin in the buttons of login

app/assets/stylesheets/pages/accounts/_show.scss, app/javascript/controllers/toggle_controller.js, app/views/accounts/show.html.erb
Started creating the controller on the user dashboard.
=> Started creating the controller on the user dashboard

app/views/chatrooms/index.html.erb
Iterated over the current users open chatrooms to display the image of either the event of the chatroom or the image of the other user.
=> photos for each chat now appear in the chatrooms index

app/views/accounts/show.html.erb, app/views/devise/registrations/edit.html.erb
Added a link for a user to be able to edit their account details with the appropriate fields
=> Added link to user account edit page with appropriate fields

app/controllers/events_controller.rb, app/controllers/users_controller.rb, app/views/events/index.html.erb, app/views/users/index.html.erb
Changed search functionality to display no results if no search results were found.
=> Added no results to be returned when no searchbar results

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/events/_show.scss, app/views/chatrooms/show.html.erb, app/views/messages/_messages.html.erb, app/views/messages/_new.html.erb, app/views/notifications/index.html.erb
style events chat and individual chat. Also put limit notifications up to 40 (was 20 before)
=> individual chat and event chat style

app/javascript/controllers/toggle_controller.js, app/views/accounts/show.html.erb, app/views/events/show.html.erb, config/environments/production.rb
Fixed a couple of bugs relating to the user dashboard and displaying appropriate messages
=> User profile adjustments

app/views/shared/_navbar.html.erb
Changed 'profile' to 'dashboard' on the navbar dropdown.
=> Changed 'profile' to 'dashboard'

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_form_legend_clear.scss, app/views/devise/registrations/edit.html.erb
sign up, sign in, create event and edit account forms style. Text is now black so is more readable, style buttons, take out the green border from forms.
=> forms styling

app/controllers/events_controller.rb, app/controllers/messages_controller.rb, app/models/user.rb, app/views/notifications/index.html.erb
A notification is now created for attendees of an event if the event is deleted
=> Users now receive notification if event deleted

app/assets/stylesheets/pages/accounts/_show.scss, app/views/accounts/show.html.erb
Making some style changes to the user dashboard.
=> Making some style changes to the user dashboard

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_notification.scss, app/views/chatrooms/index.html.erb, app/views/notifications/index.html.erb
chat page styling, similar to notifications style
=> chats page style

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_notification.scss, app/views/chatrooms/show.html.erb
Added a return link from chatroom back to the specific event.
=> Added a return link from chatroom back to the specific event

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form_legend_clear.scss, app/assets/stylesheets/components/_link.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/views/devise/registrations/edit.html.erb, app/views/devise/shared/_links.html.erb, app/views/events/_form.html.erb
forms style. 
Change green color from navbar and footer to make it more redable
=> change green color, style all forms

app/assets/stylesheets/components/_card.scss
Changed justify-content property to flex-start for better styling.
=> Changed justify-content property to flex-start for better styling

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_link.scss, app/assets/stylesheets/components/_notification.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/accounts/show.html.erb, app/views/notifications/index.html.erb
Fixed issues with anchor tags being the same colour as the background.
=> Fixed issues with anchor tags being the same colour as the background

app/assets/stylesheets/components/_navbar.scss
Added an orange colour to the navbar links on hover.
=> Added an orange colour to the navbar links on hover

app/assets/stylesheets/components/_footer.scss
Altered footer so that position is not fixed anymore.
=> Altered footer so that position is not fixed anymore

app/views/devise/registrations/new.html.erb
Altered devise registration validation field.
=> Altered devise registration validation field

app/controllers/chatrooms_controller.rb, app/views/chatrooms/show.html.erb, app/views/events/index.html.erb
Added a link in direct user chats so you are able to click on the name of the user and go to their profile page.
=> Added link in firect user chat to user

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/accounts/_show.scss, app/assets/stylesheets/pages/events/_show.scss, app/views/accounts/show.html.erb
Aligned positioning of edit button so that it is centered.
=> Aligned positioning of edit button so that it is centered

app/views/devise/registrations/edit.html.erb
Changed Devise validation on edit account feature.
=> Changed Devise validation on edit account feature

app/views/chatrooms/show.html.erb, app/views/layouts/application.html.erb
Made changes so that footer was consistent on every page.
=> Made changes so that footer was consistent on every page

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_notification.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/accounts/_show.scss, app/views/events/index.html.erb, app/views/layouts/application.html.erb
Added the font of Roboto to the body of the page.
=> Added the font of Roboto to the body of the page

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
Added a font to the brand name.
=> Added a font to the brand name

app/assets/stylesheets/components/_map.scss
Adjusted positioning of map logo
=> Adjusted positioning of map logo

config/meta.yml
Added meta files on config meta.yml.
=> Added meta files on config meta.yml

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Added font colour to nav bar

db/seeds.rb
add more seeds, users, events, notifications, chats, messages, attending events
=> seed with users, events, notifications and chats

db/seeds.rb
=> change image from user

app/views/users/show.html.erb
User chat button wasn´t showing, fixed unless statement in the user show.
=> fix-user-chat-button

db/seeds.rb
add attendees to football match for the purpose of presentation. And change creator of one event
=> minor changes to seeds

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/views/events/index.html.erb, app/views/users/index.html.erb
=> Changed index responsiveness

app/assets/stylesheets/components/_card.scss
fixed responsiveness for show pages. Only will apply when screen is big.
=> fix responsive only apply if screen is big

app/assets/stylesheets/components/_button.scss, app/views/chatrooms/show.html.erb, app/views/events/show.html.erb
Updated the responsiveness on some of the buttons and cleaned some code.
=> Updated the responsiveness on some of the buttons and cleaned some code

app/views/events/_form.html.erb, db/seeds.rb
change address from DB Eiffel Tower and Dali museum, coordinates wasn't showing correct in the map.
=> change address from DB to show map better

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_home.scss, app/views/accounts/show.html.erb, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb
Improved the code using the DRY principle, removing unnecessary lines.
=> Improved code using the DRY principle, removing unnecessary lines

app/views/events/index.html.erb, app/views/events/show.html.erb
Updated indentation on the events show and index pages.
=> Updated indentation on the events show and index pages

app/javascript/controllers/toggle_controller.js, app/views/events/index.html.erb
fix the map, the cards are not showing when the map is clicked
=> map showing without the cards when togggle
